# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='content',
        ),
    ]
