# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20171208_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.CharField(max_length=100),
        ),
    ]
